language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

services:
  - mysql
  - postgresql
  - docker

before_script:
  - git clone https://github.com/fate0/xmark.git
  - cd xmark && phpize && ./configure && make && cd ..
  - mv ./xmark/modules ./modules
  - composer install

script:
  - php -n -c travis-php.ini ./vendor/bin/phpunit -c phpunit.xml

after_success:
  - docker build -t prvd-dvwa:latest ./dvwa
  - docker tag prvd-dvwa:latest fate0/prvd-dvwa:latest
  - docker build -t prvd:latest ./
  - docker tag prvd:latest fate0/prvd:latest
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push fate0/prvd-dvwa:latest
  - docker push fate0/prvd:latest
